import { Show } from 'solid-js';
import {
  store,
  reorderTask,
  setActiveTask,
  updateTaskName,
  collapseTask,
  getTaskDotStatus,
  getTaskAttentionState,
  toggleTaskFocusMode,
  clearTaskLandingReview,
  getPrChecks,
} from '../store/store';
import { EditableText, type EditableTextHandle } from './EditableText';
import { IconButton } from './IconButton';
import { StatusDot } from './StatusDot';
import { CheckIcon, CloseIcon } from './icons';
import { theme } from '../lib/theme';
import { badgeStyle } from '../lib/badgeStyle';
import { handleDragReorder } from '../lib/dragReorder';
import { getTaskDockerBadgeLabel } from '../lib/docker';
import { displayTaskNameFromPrompt, shouldUsePromptDerivedTaskName } from '../lib/clean-task-name';
import type { Task } from '../store/types';
import { isLandedTaskState } from '../store/landing';

interface TaskTitleBarProps {
  task: Task;
  isActive: boolean;
  onClose: () => void;
  onMerge: () => void;
  onPush: () => void;
  pushing: boolean;
  pushSuccess: boolean;
  onTitleEditRef: (h: EditableTextHandle) => void;
}

export function TaskTitleBar(props: TaskTitleBarProps) {
  const dockerBadgeLabel = () => getTaskDockerBadgeLabel(props.task.dockerSource);
  const isLandedTask = () => isLandedTaskState(props.task.landingState);
  const landingBadge = () => {
    switch (props.task.landingState) {
      case 'landed_pending_review':
        return { label: 'Landed', color: theme.success, title: 'Landed — pending review' };
      case 'landed_cleanup_failed':
        return {
          label: 'Cleanup failed',
          color: theme.warning,
          title: props.task.landingReason ?? 'Landed, but cleanup failed',
        };
      case 'landing_escalated':
        return {
          label: 'Landing blocked',
          color: theme.warning,
          title: props.task.landingReason ?? 'Landing needs attention',
        };
      case 'landing_failed':
        return {
          label: 'Landing failed',
          color: theme.error,
          title: props.task.landingReason ?? 'Landing failed',
        };
      case 'reviewed':
        return { label: 'Reviewed', color: theme.fgMuted, title: 'Landing reviewed' };
      default:
        return null;
    }
  };
  const verificationBadge = () => {
    const checks = props.task.verification?.checks;
    if (!checks?.length) return null;
    if (checks.every((check) => check.result === 'passed')) {
      return {
        label: `Verified ${checks.length}`,
        color: theme.success,
        title: checks.map((check) => `${check.name}: ${check.command}`).join('\n'),
      };
    }
    const failed = checks.find((check) => check.result !== 'passed');
    return {
      label: failed?.result === 'blocked' ? 'Verification blocked' : 'Verification failed',
      color: theme.warning,
      title: failed
        ? `${failed.name}: ${failed.command}${failed.reason ? `\n${failed.reason}` : ''}`
        : 'Verification did not pass',
    };
  };
  const titleLabel = () => {
    const initialPrompt = props.task.savedInitialPrompt?.trim();
    if (
      !initialPrompt ||
      !shouldUsePromptDerivedTaskName(
        props.task.name,
        initialPrompt,
        props.task.nameIsAutoGenerated,
      )
    ) {
      return props.task.name;
    }
    return displayTaskNameFromPrompt(initialPrompt) || props.task.name;
  };
  const ciChecks = () => {
    const c = getPrChecks(props.task.id);
    return c && c.overall !== 'none' ? c : null;
  };
  const ciTitle = (): string => {
    const c = ciChecks();
    if (!c) return '';
    if (c.overall === 'pending') {
      return `CI running — ${c.pending} pending, ${c.passing} passing${c.failing ? `, ${c.failing} failing` : ''}`;
    }
    if (c.overall === 'success') {
      return `CI passed — ${c.passing} check${c.passing === 1 ? '' : 's'}`;
    }
    return `CI failed — ${c.failing} failing, ${c.passing} passing${c.pending ? `, ${c.pending} pending` : ''}`;
  };
  const pushTitle = () => {
    const ci = ciTitle();
    return ci ? `Push to remote\n${ci}` : 'Push to remote';
  };

  function handleTitleMouseDown(e: MouseEvent) {
    handleDragReorder(e, {
      itemId: props.task.id,
      getTaskOrder: () => store.taskOrder,
      onReorder: reorderTask,
      onTap: () => setActiveTask(props.task.id),
    });
  }

  return (
    <div
      class={`task-title-bar${props.isActive ? ' island-header-active' : ''}`}
      style={{
        display: 'flex',
        'align-items': 'center',
        'justify-content': 'space-between',
        padding: '0 10px',
        height: '100%',
        background: 'transparent',
        'border-bottom': `1px solid ${theme.border}`,
        'user-select': 'none',
        cursor: 'grab',
      }}
      onMouseDown={handleTitleMouseDown}
    >
      <div
        style={{
          overflow: 'hidden',
          flex: '1',
          'min-width': '0',
          display: 'flex',
          'align-items': 'center',
          gap: '8px',
        }}
      >
        <StatusDot
          status={getTaskDotStatus(props.task.id)}
          size="md"
          attention={getTaskAttentionState(props.task.id)}
        />
        <Show when={props.task.gitIsolation === 'direct'}>
          <span style={badgeStyle(theme.warning)}>{props.task.branchName}</span>
        </Show>
        <Show when={props.task.gitIsolation === 'none'}>
          <span style={badgeStyle(theme.fgMuted)}>no git</span>
        </Show>
        <Show when={props.task.dockerMode}>
          <span style={badgeStyle(theme.fgMuted)} title={props.task.dockerImage}>
            {dockerBadgeLabel()}
          </span>
        </Show>
        <Show when={props.task.externalWorktree}>
          <span style={badgeStyle(theme.accent)}>Imported</span>
        </Show>
        <Show when={props.task.needsReview}>
          <span
            style={badgeStyle(theme.warning)}
            title={props.task.landingReason ?? 'Review this task'}
          >
            Review
          </span>
        </Show>
        <Show when={landingBadge()}>
          {(badge) => (
            <button
              style={{
                ...badgeStyle(badge().color),
                cursor: props.task.landingState === 'landed_pending_review' ? 'pointer' : 'default',
              }}
              title={
                props.task.landingState === 'landed_pending_review'
                  ? `${badge().title}. Click to mark reviewed.`
                  : badge().title
              }
              onClick={(e) => {
                e.stopPropagation();
                if (props.task.landingState === 'landed_pending_review') {
                  clearTaskLandingReview(props.task.id);
                }
              }}
            >
              {badge().label}
            </button>
          )}
        </Show>
        <Show when={verificationBadge()}>
          {(badge) => (
            <span style={badgeStyle(badge().color)} title={badge().title}>
              {badge().label}
            </span>
          )}
        </Show>
        <EditableText
          value={titleLabel()}
          onCommit={(v) => updateTaskName(props.task.id, v)}
          class="editable-text"
          title={props.task.savedInitialPrompt}
          ref={(h) => props.onTitleEditRef(h)}
        />
      </div>
      <div style={{ display: 'flex', gap: '4px', 'margin-left': '8px', 'flex-shrink': '0' }}>
        <Show when={props.task.gitIsolation === 'worktree' && !isLandedTask()}>
          <IconButton
            icon={
              <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                <path d="M5.45 5.154A4.25 4.25 0 0 0 9.25 7.5h1.378a2.251 2.251 0 1 1 0 1.5H9.25A5.734 5.734 0 0 1 5 7.123v3.505a2.25 2.25 0 1 1-1.5 0V5.372a2.25 2.25 0 1 1 1.95-.218ZM4.25 13.5a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Zm8.5-4.5a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5ZM5 3.25a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0Z" />
              </svg>
            }
            onClick={() => props.onMerge()}
            title={props.task.baseBranch ? `Merge into ${props.task.baseBranch}` : 'Merge'}
          />
          <div style={{ position: 'relative', display: 'inline-flex' }}>
            <Show
              when={!props.pushing}
              fallback={
                <div
                  style={{
                    display: 'inline-flex',
                    'align-items': 'center',
                    'justify-content': 'center',
                    padding: '4px',
                    border: `1px solid ${theme.border}`,
                    'border-radius': '6px',
                  }}
                >
                  <span class="inline-spinner" style={{ width: '14px', height: '14px' }} />
                </div>
              }
            >
              <IconButton
                icon={
                  <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                    <path
                      d="M4.75 8a.75.75 0 0 1 .75-.75h5.19L8.22 4.78a.75.75 0 0 1 1.06-1.06l3.5 3.5a.75.75 0 0 1 0 1.06l-3.5 3.5a.75.75 0 1 1-1.06-1.06l2.47-2.47H5.5A.75.75 0 0 1 4.75 8Z"
                      transform="rotate(-90 8 8)"
                    />
                  </svg>
                }
                onClick={() => props.onPush()}
                title={pushTitle()}
              />
            </Show>
            <Show
              when={ciChecks()}
              fallback={
                <Show when={props.pushSuccess}>
                  <div
                    style={{
                      position: 'absolute',
                      bottom: '-4px',
                      right: '-4px',
                      width: '12px',
                      height: '12px',
                      'border-radius': '50%',
                      background: theme.success,
                      display: 'flex',
                      'align-items': 'center',
                      'justify-content': 'center',
                      'pointer-events': 'none',
                    }}
                  >
                    <svg width="8" height="8" viewBox="0 0 16 16" fill="white">
                      <path d="M13.78 4.22a.75.75 0 0 1 0 1.06l-7.25 7.25a.75.75 0 0 1-1.06 0L2.22 9.28a.75.75 0 0 1 1.06-1.06L6 10.94l6.72-6.72a.75.75 0 0 1 1.06 0Z" />
                    </svg>
                  </div>
                </Show>
              }
            >
              {(c) => (
                <div
                  style={{
                    position: 'absolute',
                    bottom: '-4px',
                    right: '-4px',
                    width: '14px',
                    height: '14px',
                    'border-radius': '50%',
                    background:
                      c().overall === 'pending'
                        ? 'transparent'
                        : c().overall === 'success'
                          ? theme.success
                          : theme.error,
                    display: 'flex',
                    'align-items': 'center',
                    'justify-content': 'center',
                    color: c().overall === 'pending' ? theme.warning : 'white',
                    'pointer-events': 'none',
                  }}
                >
                  <Show when={c().overall === 'pending'}>
                    <span class="inline-spinner" style={{ width: '12px', height: '12px' }} />
                  </Show>
                  <Show when={c().overall === 'success'}>
                    <CheckIcon size={9} />
                  </Show>
                  <Show when={c().overall === 'failure'}>
                    <CloseIcon size={9} />
                  </Show>
                </div>
              )}
            </Show>
          </div>
        </Show>
        <IconButton
          icon={
            store.focusMode ? (
              <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                <path d="M5.5 2.75A.75.75 0 0 0 4.75 2H2.5a.5.5 0 0 0-.5.5v2.25a.75.75 0 0 0 1.5 0V3.5h1.25a.75.75 0 0 0 .75-.75ZM11.25 2a.75.75 0 0 0 0 1.5H12.5v1.25a.75.75 0 0 0 1.5 0V2.5a.5.5 0 0 0-.5-.5h-2.25ZM3.5 11.25a.75.75 0 0 0-1.5 0V13.5a.5.5 0 0 0 .5.5h2.25a.75.75 0 0 0 0-1.5H3.5v-1.25ZM14 11.25a.75.75 0 0 0-1.5 0v1.25h-1.25a.75.75 0 0 0 0 1.5H13.5a.5.5 0 0 0 .5-.5v-2.25Z" />
              </svg>
            ) : (
              <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                <path d="M2.75 5.5A.75.75 0 0 0 3.5 4.75V3.5h1.25a.75.75 0 0 0 0-1.5H2.5a.5.5 0 0 0-.5.5v2.25c0 .414.336.75.75.75ZM12.5 4.75a.75.75 0 0 0 1.5 0V2.5a.5.5 0 0 0-.5-.5h-2.25a.75.75 0 0 0 0 1.5h1.25v1.25ZM3.5 11.25a.75.75 0 0 0-1.5 0V13.5a.5.5 0 0 0 .5.5h2.25a.75.75 0 0 0 0-1.5H3.5v-1.25ZM13.25 10.5a.75.75 0 0 0-.75.75v1.25h-1.25a.75.75 0 0 0 0 1.5H13.5a.5.5 0 0 0 .5-.5v-2.25a.75.75 0 0 0-.75-.75Z" />
              </svg>
            )
          }
          onClick={() => {
            toggleTaskFocusMode(props.task.id);
          }}
          title={store.focusMode ? 'Exit focus mode' : 'Focus on this task'}
        />
        <Show when={!props.task.coordinatorMode}>
          <IconButton
            icon={
              <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
                <path d="M2 8a.75.75 0 0 1 .75-.75h10.5a.75.75 0 0 1 0 1.5H2.75A.75.75 0 0 1 2 8Z" />
              </svg>
            }
            onClick={() => collapseTask(props.task.id)}
            title="Collapse task"
          />
        </Show>
        <IconButton icon={<CloseIcon />} onClick={() => props.onClose()} title="Close task" />
      </div>
    </div>
  );
}
